version: '3.8'

services:
  neo-vision:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
