services:
  neo-vision:
    build: .
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 4173"
